---
title: "8131 HW10"
output: html_document
date: "2023-04-30"
---

```{r}
library(dplyr)
library(survival)
install.packages("ggfortify")
library(ggfortify)
library(KMsurv)
```
# problem1
```{r}
data = tibble(
  time = c(c(4, 12, 15, 21, 23), c(2, 6, 8, 10, 19)), 
  censor = c(c(1, 0, 1, 0, 1), c(1, 0, 0, 1, 1)),
  group = c(rep(1, 5), rep(2, 5))
)

log_rank_test = survdiff(Surv(time, censor) ~ group, data = data)
log_rank_test
autoplot(survfit(Surv(time, censor) ~ group, data = data))
pvalue = round(1 - pchisq(log_rank_test$chisq, 1), 3)
```

# problem2
```{r}
data("kidtran")
# male
survdiff(Surv(time, delta)~ gender + race, data = kidtran, subset = (gender == 1))
# female
survdiff(Surv(time, delta)~ gender + race, data = kidtran, subset = (gender == 2))
```

# problem3
```{r}
data("larynx")
larynx = larynx %>% 
  mutate(
    Z1 = as.factor(if_else(stage == 2,1,0)),
    Z2 = as.factor(if_else(stage == 3,1,0)),
    Z3 = as.factor(if_else(stage == 4,1,0)),
    Z4 = age
  )

res3 = coxph(Surv(time, delta) ~ Z1 + Z2 + Z3 + Z4 + Z1 * Z4, data = larynx, ties = 'breslow')
t(res3$coefficients) %>% knitr::kable()
res3
```


